/*
 * This file is generated by jOOQ.
 */
package net.daester.david.haveIBeenPwnedImporter.jooq.tables.references


import net.daester.david.haveIBeenPwnedImporter.jooq.tables.Hash
import net.daester.david.haveIBeenPwnedImporter.jooq.tables.HashPrefixFileHashCountView



/**
 * The table <code>pwned.hash</code>.
 */
val HASH: Hash = Hash.HASH

/**
 * The table <code>pwned.hash_prefix_file_hash_count_view</code>.
 */
val HASH_PREFIX_FILE_HASH_COUNT_VIEW: HashPrefixFileHashCountView = HashPrefixFileHashCountView.HASH_PREFIX_FILE_HASH_COUNT_VIEW
