/*
 * This file is generated by jOOQ.
 */
package net.daester.david.haveIBeenPwnedImporter.jooq


import kotlin.collections.List

import net.daester.david.haveIBeenPwnedImporter.jooq.tables.Hash
import net.daester.david.haveIBeenPwnedImporter.jooq.tables.HashPrefixFileHashCountView

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Pwned : SchemaImpl("pwned", DefaultCatalog.DEFAULT_CATALOG) {
    companion object {

        /**
         * The reference instance of <code>pwned</code>
         */
        val PWNED: Pwned = Pwned()
    }

    /**
     * The table <code>pwned.hash</code>.
     */
    val HASH: Hash get() = Hash.HASH

    /**
     * The table <code>pwned.hash_prefix_file_hash_count_view</code>.
     */
    val HASH_PREFIX_FILE_HASH_COUNT_VIEW: HashPrefixFileHashCountView get() = HashPrefixFileHashCountView.HASH_PREFIX_FILE_HASH_COUNT_VIEW

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Hash.HASH,
        HashPrefixFileHashCountView.HASH_PREFIX_FILE_HASH_COUNT_VIEW
    )
}
