/*
 * This file is generated by jOOQ.
 */
package net.daester.david.haveIBeenPwnedImporter.jooq.tables


import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import net.daester.david.haveIBeenPwnedImporter.jooq.Pwned
import net.daester.david.haveIBeenPwnedImporter.jooq.indexes.HASH_HASH_FILE_HASH_INDEX
import net.daester.david.haveIBeenPwnedImporter.jooq.indexes.HASH_HASH_HASH_PREFIX_FILE_HASH_INDEX
import net.daester.david.haveIBeenPwnedImporter.jooq.indexes.HASH_HASH_HASH_PREFIX_HASH_SUFFIX_INDEX
import net.daester.david.haveIBeenPwnedImporter.jooq.indexes.HASH_HASH_HASH_PREFIX_OCCURRENCE_INDEX
import net.daester.david.haveIBeenPwnedImporter.jooq.indexes.HASH_HASH_OCCURRENCE_INDEX
import net.daester.david.haveIBeenPwnedImporter.jooq.tables.records.HashRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Hash(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, HashRecord>?,
    parentPath: InverseForeignKey<out Record, HashRecord>?,
    aliased: Table<HashRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<HashRecord>(
    alias,
    Pwned.PWNED,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>pwned.hash</code>
         */
        val HASH: Hash = Hash()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<HashRecord> = HashRecord::class.java

    /**
     * The column <code>pwned.hash.hash_prefix</code>.
     */
    val HASH_PREFIX: TableField<HashRecord, String?> = createField(DSL.name("hash_prefix"), SQLDataType.CHAR(5).nullable(false), this, "")

    /**
     * The column <code>pwned.hash.hash_suffix</code>.
     */
    val HASH_SUFFIX: TableField<HashRecord, String?> = createField(DSL.name("hash_suffix"), SQLDataType.CHAR(36).nullable(false), this, "")

    /**
     * The column <code>pwned.hash.occurrence</code>.
     */
    val OCCURRENCE: TableField<HashRecord, Int?> = createField(DSL.name("occurrence"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>pwned.hash.file_hash</code>.
     */
    val FILE_HASH: TableField<HashRecord, String?> = createField(DSL.name("file_hash"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>pwned.hash.last_update</code>.
     */
    val LAST_UPDATE: TableField<HashRecord, LocalDateTime?> = createField(DSL.name("last_update"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<HashRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<HashRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<HashRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>pwned.hash</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>pwned.hash</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>pwned.hash</code> table reference
     */
    constructor(): this(DSL.name("hash"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Pwned.PWNED
    override fun getIndexes(): List<Index> = listOf(HASH_HASH_FILE_HASH_INDEX, HASH_HASH_HASH_PREFIX_FILE_HASH_INDEX, HASH_HASH_HASH_PREFIX_HASH_SUFFIX_INDEX, HASH_HASH_HASH_PREFIX_OCCURRENCE_INDEX, HASH_HASH_OCCURRENCE_INDEX)
    override fun `as`(alias: String): Hash = Hash(DSL.name(alias), this)
    override fun `as`(alias: Name): Hash = Hash(alias, this)
    override fun `as`(alias: Table<*>): Hash = Hash(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Hash = Hash(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Hash = Hash(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Hash = Hash(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Hash = Hash(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Hash = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Hash = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Hash = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Hash = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Hash = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Hash = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Hash = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Hash = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Hash = where(DSL.notExists(select))
}
