/*
 * This file is generated by jOOQ.
 */
package net.daester.david.haveIBeenPwnedImporter.jooq.indexes


import net.daester.david.haveIBeenPwnedImporter.jooq.tables.Hash

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val HASH_HASH_FILE_HASH_INDEX: Index = Internal.createIndex(DSL.name("hash_file_hash_index"), Hash.HASH, arrayOf(Hash.HASH.FILE_HASH), false)
val HASH_HASH_HASH_PREFIX_FILE_HASH_INDEX: Index = Internal.createIndex(DSL.name("hash_hash_prefix_file_hash_index"), Hash.HASH, arrayOf(Hash.HASH.HASH_PREFIX, Hash.HASH.FILE_HASH), false)
val HASH_HASH_HASH_PREFIX_HASH_SUFFIX_INDEX: Index = Internal.createIndex(DSL.name("hash_hash_prefix_hash_suffix_index"), Hash.HASH, arrayOf(Hash.HASH.HASH_PREFIX, Hash.HASH.HASH_SUFFIX), false)
val HASH_HASH_HASH_PREFIX_OCCURRENCE_INDEX: Index = Internal.createIndex(DSL.name("hash_hash_prefix_occurrence_index"), Hash.HASH, arrayOf(Hash.HASH.HASH_PREFIX, Hash.HASH.OCCURRENCE), false)
val HASH_HASH_OCCURRENCE_INDEX: Index = Internal.createIndex(DSL.name("hash_occurrence_index"), Hash.HASH, arrayOf(Hash.HASH.OCCURRENCE), false)
